name: cf21_map_flutter
description: CF21 Creator Booth Map Viewer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - data/map.json
    - data/creator-data-initial.json
    - assets/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          

